/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PjCodeBlock: typeof import('./components/PjCodeBlock.vue')['default']
    PjFooter: typeof import('./components/PjFooter.vue')['default']
    PjHeader: typeof import('./components/PjHeader.vue')['default']
    PjNavbar: typeof import('./components/PjNavbar.vue')['default']
    PjSidebar: typeof import('./components/PjSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VvAction: typeof import('@volverjs/ui-vue/components')['VvAction']
    VvButton: typeof import('@volverjs/ui-vue/components')['VvButton']
    VvButtonGroup: typeof import('@volverjs/ui-vue/components')['VvButtonGroup']
  }
}
